/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivosRouteImport } from './routes/activos'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AportantesRouteImport } from './routes/aportantes'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as ComisionesRouteImport } from './routes/comisiones'
import { Route as CuentasRouteImport } from './routes/cuentas'
import { Route as DemografiaRouteImport } from './routes/demografia'
import { Route as IsinRouteImport } from './routes/isin'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as RendimientoRouteImport } from './routes/rendimiento'
import { Route as TransferenciasRouteImport } from './routes/transferencias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivosRoute = ActivosRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AportantesRoute = AportantesRouteImport.update({
  id: '/aportantes',
  path: '/aportantes',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComisionesRoute = ComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasRoute = CuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemografiaRoute = DemografiaRouteImport.update({
  id: '/demografia',
  path: '/demografia',
  getParentRoute: () => rootRouteImport,
} as any)
const IsinRoute = IsinRouteImport.update({
  id: '/isin',
  path: '/isin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RendimientoRoute = RendimientoRouteImport.update({
  id: '/rendimiento',
  path: '/rendimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciasRoute = TransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activos': typeof ActivosRoute
  '/afiliados': typeof AfiliadosRoute
  '/aportantes': typeof AportantesRoute
  '/beneficios': typeof BeneficiosRoute
  '/comisiones': typeof ComisionesRoute
  '/cuentas': typeof CuentasRoute
  '/demografia': typeof DemografiaRoute
  '/isin': typeof IsinRoute
  '/portafolio': typeof PortafolioRoute
  '/rendimiento': typeof RendimientoRoute
  '/transferencias': typeof TransferenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activos': typeof ActivosRoute
  '/afiliados': typeof AfiliadosRoute
  '/aportantes': typeof AportantesRoute
  '/beneficios': typeof BeneficiosRoute
  '/comisiones': typeof ComisionesRoute
  '/cuentas': typeof CuentasRoute
  '/demografia': typeof DemografiaRoute
  '/isin': typeof IsinRoute
  '/portafolio': typeof PortafolioRoute
  '/rendimiento': typeof RendimientoRoute
  '/transferencias': typeof TransferenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activos': typeof ActivosRoute
  '/afiliados': typeof AfiliadosRoute
  '/aportantes': typeof AportantesRoute
  '/beneficios': typeof BeneficiosRoute
  '/comisiones': typeof ComisionesRoute
  '/cuentas': typeof CuentasRoute
  '/demografia': typeof DemografiaRoute
  '/isin': typeof IsinRoute
  '/portafolio': typeof PortafolioRoute
  '/rendimiento': typeof RendimientoRoute
  '/transferencias': typeof TransferenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activos'
    | '/afiliados'
    | '/aportantes'
    | '/beneficios'
    | '/comisiones'
    | '/cuentas'
    | '/demografia'
    | '/isin'
    | '/portafolio'
    | '/rendimiento'
    | '/transferencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activos'
    | '/afiliados'
    | '/aportantes'
    | '/beneficios'
    | '/comisiones'
    | '/cuentas'
    | '/demografia'
    | '/isin'
    | '/portafolio'
    | '/rendimiento'
    | '/transferencias'
  id:
    | '__root__'
    | '/'
    | '/activos'
    | '/afiliados'
    | '/aportantes'
    | '/beneficios'
    | '/comisiones'
    | '/cuentas'
    | '/demografia'
    | '/isin'
    | '/portafolio'
    | '/rendimiento'
    | '/transferencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivosRoute: typeof ActivosRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AportantesRoute: typeof AportantesRoute
  BeneficiosRoute: typeof BeneficiosRoute
  ComisionesRoute: typeof ComisionesRoute
  CuentasRoute: typeof CuentasRoute
  DemografiaRoute: typeof DemografiaRoute
  IsinRoute: typeof IsinRoute
  PortafolioRoute: typeof PortafolioRoute
  RendimientoRoute: typeof RendimientoRoute
  TransferenciasRoute: typeof TransferenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activos': {
      id: '/activos'
      path: '/activos'
      fullPath: '/activos'
      preLoaderRoute: typeof ActivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aportantes': {
      id: '/aportantes'
      path: '/aportantes'
      fullPath: '/aportantes'
      preLoaderRoute: typeof AportantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comisiones': {
      id: '/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof ComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas': {
      id: '/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof CuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demografia': {
      id: '/demografia'
      path: '/demografia'
      fullPath: '/demografia'
      preLoaderRoute: typeof DemografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isin': {
      id: '/isin'
      path: '/isin'
      fullPath: '/isin'
      preLoaderRoute: typeof IsinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendimiento': {
      id: '/rendimiento'
      path: '/rendimiento'
      fullPath: '/rendimiento'
      preLoaderRoute: typeof RendimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencias': {
      id: '/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof TransferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivosRoute: ActivosRoute,
  AfiliadosRoute: AfiliadosRoute,
  AportantesRoute: AportantesRoute,
  BeneficiosRoute: BeneficiosRoute,
  ComisionesRoute: ComisionesRoute,
  CuentasRoute: CuentasRoute,
  DemografiaRoute: DemografiaRoute,
  IsinRoute: IsinRoute,
  PortafolioRoute: PortafolioRoute,
  RendimientoRoute: RendimientoRoute,
  TransferenciasRoute: TransferenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
